services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - "80:80" 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080 # Variável de ambiente para apontar ao backend
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend # Pasta onde está o projeto Node.js
      dockerfile: Dockerfile # Certifique-se de criar este Dockerfile no backend
    ports:
      - "8080:8080" # Porta 8080 para o backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=my_database
    depends_on:
      - db

  db:
    container_name: taxi_db 
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

